### ISSUE TITLE
Errors when trying to compile with godot version 4.2.1

### ISSUE THREAD

**Issue by staakman** [octetdev2/godot-gridmap-module#2]
Hi!👋 Is it possible that the current version is not compatible with godot 4.2.1? 

I get the following error: 

`modules\register_module_types.gen.cpp(60): error C3861: 'initialize_TileMap3D_module': identifier not found`
`modules\register_module_types.gen.cpp(211): error C3861: 'uninitialize_TileMap3D_module': identifier not found`

My guess is that they recently changed how they initialize models in godot 4.2.1
This is easy to fix but even after fixing that I get errors such as:

`modules\TileMap3D\editor\tile_map_3d_editor_plugin.cpp(79): error C2065: 'options': undeclared identifier`

Do you happen to know which version is compatible? 
Are you planning on making this plugin godot 4.2.1 compatible?

Thank you for your time. 

With kind regards,

Thierry

**Comment by isosphere** [comment]
The latest commit in this repo is 2022-04-27, and 4.0-stable was released on 2023-03-01. I think the target must have been a beta. 

Check out https://github.com/dmlary/godot-hex-map instead. It builds out of the box on 4.7 and is MIT licensed.
